In [ ]:
import pandas as pd #Alias to the tool that we will be consuming

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
data = pd.read_csv("purchases.csv")

In [ ]:
data.head()

  Unnamed: 0  apples  oranges
0       June       3        0
1     Robert       2        3
2       Lily       0        7
3      David       1        2

In [ ]:
data = {"Materials": ['Silk','Rose'],
        "Percent": [100,20]}



1.  Series
2.  Data Frame

In [ ]:
pandas_data = pd.DataFrame(data)
pandas_data

  Materials  Percent
0      Silk      100
1      Rose       20

In [ ]:
type(pandas_data)

pandas.core.frame.DataFrame

In [ ]:
type(pandas_data['Materials'])

pandas.core.series.Series

In [ ]:
purchases = pd.read_json("purchases.json")

In [ ]:
purchases #Columns
#Index

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [ ]:
data = {"Materials": ['Silk','Rose'],
        "Percent": [100,20]}

pandas_data = pd.DataFrame(data)
pandas_data

  Materials  Percent
0      Silk      100
1      Rose       20

In [ ]:
pandas_data = pd.DataFrame(data, index = ["Yes","No"])
pandas_data

    Materials  Percent
Yes      Silk      100
No       Rose       20

In [ ]:
data = {"Materials": ['Silk','Rose'],
        "Percent": [100,20],
        "Std": [1,2]}

In [ ]:
pandas_data = pd.DataFrame(data, index = ["True","False"])
#index is just an alias to the row as names
pandas_data

      Materials  Percent  Std
True       Silk      100    1
False      Rose       20    2

In [ ]:
pandas_data = pd.DataFrame(data)
pandas_data

  Materials  Percent  Std
0      Silk      100    1
1      Rose       20    2

In [ ]:
pd.DataFrame?

In [ ]:
#Column - Columns in pandas
#Index - Name given to rows

In [ ]:
no_colname = pd.read_csv("purchases_withoutcolums.csv")

In [ ]:
no_colname

  Unnamed: 0  Unnamed: 1  Unnamed: 2
0       June           3           0
1     Robert           2           3
2       Lily           0           7
3      David           1           2

In [ ]:
no_colname.columns = ['1','2','3']

In [ ]:
no_colname

        1  2  3
0    June  3  0
1  Robert  2  3
2    Lily  0  7
3   David  1  2

In [ ]:
#Pyspark - BigData - HeavyDuty Pickup Truck
#Pandas Dataframe - Thar - High performace Cars

In [ ]:
!pip install pysqlite3

Collecting pysqlite3
  Downloading pysqlite3-0.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Downloading pysqlite3-0.6.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 43.9 MB/s eta 0:00:00
Installing collected packages: pysqlite3
Successfully installed pysqlite3-0.6.0

In [ ]:
import sqlite3

In [ ]:
con = sqlite3.connect("database.db")

In [ ]:
df = pd.read_sql_query("SELECT * FROM purchases",con)

In [ ]:
df

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7
3   David       1        2

In [ ]:
df.set_index("index")

        apples  oranges
index
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [ ]:
df.head(2)

    index  apples  oranges
0    June       3        0
1  Robert       2        3

In [ ]:
df.head(3)

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7

In [ ]:
df.head()

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7
3   David       1        2

In [ ]:
df.tail()

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2    Lily       0        7
3   David       1        2

In [ ]:
df.tail(1)

   index  apples  oranges
3  David       1        2

In [ ]:
MoviesData = pd.read_csv("IMDB-Movie-Data.csv")

In [ ]:
MoviesData.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
MoviesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [ ]:
MoviesData.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [ ]:
import pandas as pd

In [ ]:
MoviesData = pd.read_csv("IMDB-Movie-Data.csv")

In [ ]:
MoviesData.shape

(1000, 12)

In [ ]:
MoviesData.tail(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [ ]:
MoviesData.append?

Object `MoviesData.append` not found.

In [ ]:
#MoviesData_duplicates = MoviesData.append(MoviesData) #This is removed / deprecited
#MoviesData_duplicates

#https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.DataFrame.append.html

In [ ]:
Movie_data_duplicates = pd.concat([MoviesData,MoviesData])

In [ ]:
Movie_data_duplicates.shape

(2000, 12)

In [ ]:
#The first impurity in the dataset is the presence of duplcates - Do distributions also represent frequency
temp_df = Movie_data_duplicates.drop_duplicates()

In [ ]:
temp_df.shape

(1000, 12)

In [ ]:
Movie_data_duplicates.drop_duplicates(inplace = True) #inplace operations are now arguments

In [ ]:
Movie_data_duplicates.shape

(1000, 12)

In [ ]:
Movie_data_duplicates = pd.concat([MoviesData,MoviesData])

In [ ]:
lst = [-1,2,3,4]
lst

[-1, 2, 3, 4]

In [ ]:
#lst = lst.append(10) #Reassignig
lst.append(10) #inplace operations

In [ ]:
lst

[-1, 2, 3, 4, 10]

In [ ]:
Movie_data_duplicates.shape

(1200, 12)

In [ ]:
Movie_data_duplicates.drop_duplicates(inplace = True,keep = False) #Keep will drop all the duplicates.. If two rows are the same then both the rows will be dropped

In [ ]:
Movie_data_duplicates.shape

(800, 12)

In [ ]:
MoviesData.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [ ]:
#Dictionary style
MoviesData.rename(columns = {"Runtime (Minutes)": "Runtime", "Revenue (Millions)": "Revenue"}, inplace = True)

In [ ]:
MoviesData.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
#list style change
MoviesData.columns = ['rank', 'title', 'genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime', 'Rating', 'Votes', 'Revenue', 'Metascore']

In [ ]:
MoviesData.head()

,rank,title,genre,Description,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
MoviesData[1]

KeyError: 1

In [ ]:
Pandas Data Frame -> Pandas 1D Series -> Data

In [ ]:
MoviesData['rank']

0         1
1         2
2         3
3         4
4         5
       ...
995     996
996     997
997     998
998     999
999    1000
Name: rank, Length: 1000, dtype: int64

In [ ]:
MoviesData['genre']

0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
                 ...
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy
Name: genre, Length: 1000, dtype: object

In [ ]:
#Access prometheus - Via indexing

In [ ]:
MoviesData['title'][1]

'Prometheus'

In [ ]:
#[rowIndex,columnIndex]

In [ ]:
MoviesData.iloc[1,1] # index Location

'Prometheus'

In [ ]:
MoviesData.iloc[:10,1]

0    Guardians of the Galaxy
1                 Prometheus
2                      Split
3                       Sing
4              Suicide Squad
5             The Great Wall
6                 La La Land
7                   Mindhorn
8         The Lost City of Z
9                 Passengers
Name: title, dtype: object

In [ ]:
MoviesData.iloc[:10,:5]

,rank,title,genre,Description,Director
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum

In [ ]:
#MoviesData.merge()

In [ ]:
MoviesData.iloc[5,:]

rank                                                           6
title                                             The Great Wall
genre                                   Action,Adventure,Fantasy
Description    European mercenaries searching for black powde...
Director                                             Yimou Zhang
Actors             Matt Damon, Tian Jing, Willem Dafoe, Andy Lau
Year                                                        2016
Runtime                                                      103
Rating                                                       6.1
Votes                                                      56036
Revenue                                                    45.13
Metascore                                                   42.0
Name: 5, dtype: object

In [ ]:
type(MoviesData.iloc[5])

pandas.core.series.Series

In [ ]:
MoviesData.iloc[5] #Rows is a pandas series - Row object

rank                                                           6
title                                             The Great Wall
genre                                   Action,Adventure,Fantasy
Description    European mercenaries searching for black powde...
Director                                             Yimou Zhang
Actors             Matt Damon, Tian Jing, Willem Dafoe, Andy Lau
Year                                                        2016
Runtime                                                      103
Rating                                                       6.1
Votes                                                      56036
Revenue                                                    45.13
Metascore                                                   42.0
Name: 5, dtype: object

In [ ]:
MoviesData.iloc[5:6] #Rows is a pandas series - Row object

,rank,title,genre,Description,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0

In [ ]:
MoviesData.iloc[:5]

,rank,title,genre,Description,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
MoviesData.iloc[5,'title']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [ ]:
MoviesData.iloc[[10,20,30],[0,1,6]]

    rank                                    title  Year
10    11  Fantastic Beasts and Where to Find Them  2016
20    21                                     Gold  2016
30    31                                 Why Him?  2016

In [ ]:
MoviesData.iloc[[10,20,30],['title',1,6]] #indexing based

IndexError: .iloc requires numeric indexers, got ['title' '1' '6']

In [ ]:
#Index - Rows in pandas
#columns - columns

In [ ]:
import pandas as pd
MoviesData =  pd.read_csv("https://raw.githubusercontent.com/Laxminarayen/InceptezGenAI-Batch26/refs/heads/main/08.%20Python_Day7_Pandas/IMDB-Movie-Data.csv")

In [ ]:
MoviesData.iloc[[10,20,30],[0,1,6]]

    rank                                    title  Year
10    11  Fantastic Beasts and Where to Find Them  2016
20    21                                     Gold  2016
30    31                                 Why Him?  2016

In [ ]:
MoviesData.head()

In [ ]:
MoviesData.iloc[[5]] #Rows is a pandas series - Row object

,rank,title,genre,Description,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0

In [ ]:
#SQL - Knife - ETL
#Pandas - Swiss - before building predictions we will 2nd round of cleaning

In [ ]:
#iloc - uses co-ordinates (int) (15' east 13' south)
#loc - Names (MTR restaurant in bangalore)

In [ ]:
MoviesData.iloc[10,'title']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [ ]:
MoviesData.loc[10,'title']

'Fantastic Beasts and Where to Find Them'

In [ ]:
MoviesData.loc[MoviesData['rank']==10,'title'] #Alphas or boolean

9    Passengers
Name: title, dtype: object

In [ ]:
MoviesData.loc[MoviesData['rank']<10,'title'] #It is basically WHERE clause and SELECT Statement..

0    Guardians of the Galaxy
1                 Prometheus
2                      Split
3                       Sing
4              Suicide Squad
5             The Great Wall
6                 La La Land
7                   Mindhorn
8         The Lost City of Z
Name: title, dtype: object

## Null values are problematic!!!!!!


1.   Removing the rows where missing values are present
2.   Replace it with statistically meaningful values

In [ ]:
MoviesData.isna().sum() #NA - Not Available

NameError: name 'MoviesData' is not defined

In [ ]:
pd.DataFrame?

#MAke sure we find what are the values converted
#to NA inside pandas

In [ ]:
MoviesData.dropna(inplace = True)

In [ ]:
MoviesData.shape

(838, 12)

In [ ]:
def rating_function(x):
  if x >=8.0:
    return "good"
  else:
    return "bad"

In [ ]:
MoviesData.head()

,rank,title,genre,Description,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
MoviesData['Rating_good_bad'] = MoviesData['Rating'].apply(rating_function) #reassignment operation

In [ ]:
MoviesData.head()

,rank,title,genre,Description,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore,Rating_good_bad
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,good
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,bad
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,bad
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,bad
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,bad